version: '3.8'

services:
  nginx:
    build:
      context: .
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    restart: always
    network_mode: "host"
